# Generated by Django 3.2.5 on 2021-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
